//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatMedic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Врачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Врачи()
        {
            this.Прием_пациентов = new HashSet<Прием_пациентов>();
        }
    
        public int Код_врача { get; set; }
        public string Фамилия_врача { get; set; }
        public string Имя_врача { get; set; }
        public string Отчество_врача { get; set; }
        public string Специальность_врача { get; set; }
        public int Процент { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Прием_пациентов> Прием_пациентов { get; set; }
    }
}
