//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatMedic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прием_пациентов
    {
        public int Код_приема { get; set; }
        public int Код_врача { get; set; }
        public int Код_пациента { get; set; }
        public System.DateTime Дата_приема { get; set; }
        public decimal Стоимость_приема { get; set; }
        public Nullable<float> Зарплата { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Пациенты Пациенты { get; set; }
    }
}
